- name: Install apache
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - 'apache2'

- name: enabled mod_rewrite
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - 'proxy'
    - 'proxy_http'
    - 'rewrite'
    - 'ssl'
  notify:
    - restart apache2

- name: Add in PATH
  lineinfile:
    path: "/etc/profile.d/apache2.sh"
    line: "export PATH=$PATH:/usr/sbin"
    state: present
    create: true
