- name: Install apache
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - 'apache2'

- name: enabled mod_rewrite
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - 'proxy'
    - 'proxy_http'
    - 'rewrite'
    - 'ssl'
  notify:
    - restart apache2

- name: Add in PATH
  lineinfile:
    path: "/etc/profile.d/apache2.sh"
    line: "export PATH=$PATH:/usr/sbin"
    state: present
    create: true

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Ensure Apache is running
  command: systemctl status apache2
  register: apache_status
  ignore_errors: yes

- name: Display Apache status
  debug:
    var: apache_status.stdout_lines
