- name: Install common dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'git'
    - 'gnupg'
    - 'lsb-release'
    - 'net-tools'
    - 'software-properties-common'
    - 'telnet'
    - 'tmux'
    - 'tree'
    - 'unzip'
    - 'vim'
    - 'wget'
    - 'zip'

- name: Add root util aliases
  lineinfile:
# path: "/root/.bash_aliases"
    path: "/root/.bashrc"
    line: "alias {{ item }}"
    state: present
    create: true
  loop: "{{ aliases }}"

- name: Add user util aliases
  lineinfile:
    path: "/home/{{ item[0] }}/.bash_aliases"
    line: "alias {{ item[1] }}"
    state: present
    create: true
    owner: "{{ item[0] }}"
    group: "{{ item[0] }}"
    mode: '644'
  with_nested:
    - "{{ users }}"
    - "{{ aliases }}"
