- name: Install common dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - 'ca-certificates'
    - 'cron'
    - 'curl'
    - 'git'
    - 'gnupg'
    - 'lsb-release'
    - 'net-tools'
    - 'rsync'
    - 'software-properties-common'
    - 'telnet'
    - 'tmux'
    - 'tree'
    - 'vim'
    - 'wget'

- name: Ensure .bash_aliases exists for root user
  copy:
    dest: "/root/.bash_aliases"
    content: "{{ lookup('file', '.bash_aliases') }}"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Ensure .bashrc sources .bash_aliases for root user
  blockinfile:
    path: "/root/.bashrc"
    block: |
      if [ -f ~/.bash_aliases ]; then
          . ~/.bash_aliases
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Source .bash_aliases"
    insertafter: EOF
    owner: "root"
    group: "root"
    mode: "0644"

- name: Ensure .bash_aliases exists for {{ item }} user
  copy:
    dest: "/home/{{ item }}/.bash_aliases"
    content: "{{ lookup('file', '.bash_aliases') }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0644"
  with_items: "{{ users }}"

- name: Ensure .bashrc sources .bash_aliases for {{ item }} user
  blockinfile:
    path: "/home/{{ item }}/.bashrc"
    block: |
      if [ -f ~/.bash_aliases ]; then
          . ~/.bash_aliases
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Source .bash_aliases"
    insertafter: EOF
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0644"
  with_items: "{{ users }}"
