---
- name: Install utils
  apt:
    name:
      - tmux
      - vim
      - curl
      - zip
      - unzip
      - tree
      - wget
      - net-tools
      - telnet
    state: latest
    update_cache: yes
...
