version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    restart: on-failure
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/mariadb/db:/var/lib/mysql
      - ./volumes/mariadb/conf:/etc/mysql/conf.d
    environment:
#      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: salut
#      MYSQL_USER: user1
#      MYSQL_PASSWORD: password1

  redis:
    container_name: redis
    image: redis
    restart: on-failure

  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
    depends_on:
      - mariadb

  php:
    container_name: php
    build: ./containers/php
    restart: on-failure
    volumes:
      - ./volumes/php/conf:/usr/local/etc/php/conf.d
      - ./volumes/app:/var/www/html
    depends_on:
      - mariadb

  apache:
    container_name: apache
    build: ./containers/apache
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./volumes/app:/var/www/html
      - ./volumes/apache/sites-enabled:/etc/apache2/sites-enabled
    depends_on:
      - mariadb
      - php

  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    restart: on-failure
    ports:
      - "1080:80"
