- name: Add ppa
  shell:
    cmd: "curl -fsSL https://deb.nodesource.com/setup_14.x | bash -"
    warn: false
    creates: "/usr/share/keyrings/nodesource.gpg"

- name: Install npm
  apt:
    name: nodejs
    update_cache: true
