---
- name: install docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
    state: present

- name: add docker repo apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: add Docker repository
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    update_cache: true

- name: install docker
  apt:
    name: 'docker-ce'
    state: present

- name: enable docker systemd service
  service:
    name: docker
    state: started
    enabled: true

- name: prepare default daemon configuration
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: set periodic docker system prune
  cron:
    name: docker-prune
    minute: 0
    hour: '*/2'
    job: 'docker container prune -f'

- name: add users to docker group
  user:
    name: '{{ item }}'
    groups: docker
    append: true
  with_items: '{{ docker_group_members }}'
  when: 'docker_group_members is defined'

- name: Install docker-compose
  apt:
    name: docker-compose
    state: present
  tags:
    - docker
...
