- name: Install common dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'software-properties-common'
    - 'gnupg'
    - 'lsb-release'

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - 'docker-ce'
    - 'docker-ce-cli'
    - 'containerd.io'
    - 'python3-pip'

- name: Enable docker systemd service
  service:
    name: docker
    state: started
    enabled: true

- name: Set periodic docker system prune
  cron:
    name: docker-prune
    minute: '0'
    hour: '*/2'
    job: 'docker container prune -f'

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    group: docker
    mode: 'u+x,g+x'

- name: Add users in docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ users }}"

- name: Install python docker sdk
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  loop:
    - 'docker'
    - 'docker-compose'
