- name: Create directory for Docker keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.asc

- name: Set permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: 'a+r'

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Set periodic docker system prune
  cron:
    name: "Prune Docker containers"
    minute: "0"
    hour: "3"
    day: "10"
    job: "/usr/bin/docker container prune -f"

- name: Enable docker systemd service
  service:
    name: docker
    state: started
    enabled: true
