- name: Install Certbot
  package: "name=certbot state=present"

- name: Install Certbot Apache plugin
  package:
    name: python3-certbot-apache
    state: present

- name: Add cron job for certbot renewal (if configured)
  cron:
    name: "Certbot automatic renewal"
    minute: "0"
    hour: "4"
    day: "11"
    job: "certbot renew --quiet"

- name: Ensure Certbot is installed
  command: certbot --version
  register: certbot_version
  ignore_errors: yes

- name: Display Certbot version
  debug:
    var: certbot_version.stdout_lines

- name: Ensure correct ownership of Certbot directories
  become: true
  file:
    path: "{{ item }}"
    owner: root
    group: www-data
    state: directory
    mode: "0750"
  loop:
    - /etc/letsencrypt/live
    - /etc/letsencrypt/archive
